BUILD_STATUS_COMPLETE = 0
BUILD_STATUS_QUEUED = 1
BUILD_STATUS_FAILED = 2
BUILD_STATUS_IN_PROGRESS = 3

BUILD_STATE_CHOICES = (
    (BUILD_STATUS_COMPLETE, 'Complete'),
    (BUILD_STATUS_QUEUED, 'Queued'),
    (BUILD_STATUS_FAILED, 'Failed'),
    (BUILD_STATUS_IN_PROGRESS, 'In Progress'),
)
